# Generated by Django 4.0.4 on 2022-05-22 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('f_description', models.TextField()),
                ('is_general_info', models.BooleanField(blank=True, default=False, null=True)),
                ('status', models.IntegerField(choices=[(0, 'blank'), (1, 'medcin'), (2, 'malady'), (3, 'Medicament'), (4, 'site')], default=0)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_c', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='annonce.forum')),
            ],
        ),
    ]
