# Generated by Django 4.0.4 on 2022-05-22 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.TextField(null=True)),
                ('diagnostique', models.TextField(null=True)),
                ('lettre', models.TextField(null=True)),
                ('rendez_vous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='cal.rdv')),
            ],
        ),
    ]
