# Generated by Django 4.0.3 on 2022-05-24 20:43

import annoying.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
        ('historique', '0002_alter_history_rendez_vous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='rendez_vous',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='cal.rdv'),
        ),
    ]
