# Generated by Django 4.0.4 on 2022-05-22 12:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('first_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=20)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='media/images/profiles')),
                ('is_patient', models.BooleanField(default=True)),
                ('is_doctor', models.BooleanField(default=False)),
                ('is_assistant', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('hist_code', models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(999999)])),
                ('is_email_verified', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('phone_number', models.CharField(blank=True, max_length=12)),
                ('diplomes_nationaux_universitaire', models.TextField(blank=True, max_length=500)),
                ('urgcontact', models.TextField(blank=True, max_length=500)),
                ('lieu_cab', models.TextField(blank=True, max_length=500)),
                ('coordonnees', models.TextField(blank=True, max_length=500)),
                ('info_pratique', models.TextField(blank=True, max_length=500)),
                ('diplomes', models.TextField(blank=True, max_length=500)),
                ('experiences', models.TextField(blank=True, max_length=500)),
                ('horaire', models.CharField(blank=True, max_length=50)),
                ('specialite', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(blank=True, default='user.svg', null=True, upload_to='account/')),
                ('public', models.BooleanField(default=True)),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
