# Generated by Django 4.0.3 on 2022-05-25 21:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.IntegerField(blank=True, max_length=10, null=True, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
